version: '3.3'

services:
  unit-webapp:
    image: ernestoe/flask-unit
    volumes:
      - ./config:/docker-entrypoint.d
      - ./log/unit.log:/var/log/unit.log
      - ./state:/var/lib/unit
      - ./webapp:/www
    ports:
      - 8080:8000
